create table Companies (
	id INT,
	company VARCHAR(50),
	Country VARCHAR(50),
	City VARCHAR(50)
);
insert into Companies (id, company, Country, City) values (1, 'Devbug', 'Peru', 'Viraco');
insert into Companies (id, company, Country, City) values (2, 'Innojam', 'China', 'Lindian');
insert into Companies (id, company, Country, City) values (3, 'Muxo', 'Colombia', 'Sabanagrande');
insert into Companies (id, company, Country, City) values (4, 'Voomm', 'Portugal', 'Vila Chã');
insert into Companies (id, company, Country, City) values (5, 'Tagpad', 'Ukraine', 'Mysove');
insert into Companies (id, company, Country, City) values (6, 'Meetz', 'Russia', 'Prochnookopskaya');
insert into Companies (id, company, Country, City) values (7, 'Meetz', 'Russia', 'Rostokino');
insert into Companies (id, company, Country, City) values (8, 'Meembee', 'Japan', 'Okazaki');
insert into Companies (id, company, Country, City) values (9, 'Digitube', 'Mexico', 'Emiliano Zapata');
insert into Companies (id, company, Country, City) values (10, 'LiveZ', 'China', 'Jiuxian');
insert into Companies (id, company, Country, City) values (11, 'Tagfeed', 'China', 'Longgang');
insert into Companies (id, company, Country, City) values (12, 'Yacero', 'Indonesia', 'Tanjungpecinan Utara');
insert into Companies (id, company, Country, City) values (13, 'Jabbersphere', 'Croatia', 'Imotski');
insert into Companies (id, company, Country, City) values (14, 'Skiba', 'Peru', 'Lajas');
insert into Companies (id, company, Country, City) values (15, 'Fadeo', 'China', 'Donggu');
insert into Companies (id, company, Country, City) values (16, 'Zooveo', 'Czech Republic', 'Krásná Hora nad Vltavou');
insert into Companies (id, company, Country, City) values (17, 'Yadel', 'Mexico', 'Guadalupe');
insert into Companies (id, company, Country, City) values (18, 'Roombo', 'Portugal', 'Conqueiros');
insert into Companies (id, company, Country, City) values (19, 'Flipstorm', 'Russia', 'Luchegorsk');
insert into Companies (id, company, Country, City) values (20, 'Youspan', 'Australia', 'Perth');
insert into Companies (id, company, Country, City) values (21, 'Feedfish', 'Philippines', 'Basista');
insert into Companies (id, company, Country, City) values (22, 'Jabbertype', 'China', 'Haoxue');
insert into Companies (id, company, Country, City) values (23, 'Blognation', 'Indonesia', 'Sidomulyo');
insert into Companies (id, company, Country, City) values (24, 'Topicware', 'Slovenia', 'Dornava');
insert into Companies (id, company, Country, City) values (25, 'Mynte', 'Portugal', 'Horta');
insert into Companies (id, company, Country, City) values (26, 'Photojam', 'Russia', 'Zuyevka');
insert into Companies (id, company, Country, City) values (27, 'DabZ', 'Ukraine', 'Verkhniy Rohachyk');
insert into Companies (id, company, Country, City) values (28, 'Skyba', 'Armenia', 'Aygezard');
insert into Companies (id, company, Country, City) values (29, 'Roodel', 'Brazil', 'Ponta Grossa');
insert into Companies (id, company, Country, City) values (30, 'Shuffletag', 'Canada', 'Richibucto');
insert into Companies (id, company, Country, City) values (31, 'Aimbu', 'France', 'Vagney');
insert into Companies (id, company, Country, City) values (32, 'Twitterworks', 'United States', 'Seattle');
insert into Companies (id, company, Country, City) values (33, 'Skyvu', 'Indonesia', 'Cermee');
insert into Companies (id, company, Country, City) values (34, 'BlogXS', 'Czech Republic', 'Nivnice');
insert into Companies (id, company, Country, City) values (35, 'Edgeblab', 'Peru', 'San Ramón');
insert into Companies (id, company, Country, City) values (36, 'Photobean', 'New Zealand', 'Nelson');
insert into Companies (id, company, Country, City) values (37, 'Brainverse', 'Indonesia', 'Haruman');
insert into Companies (id, company, Country, City) values (38, 'Lazz', 'Armenia', 'Norabats’');
insert into Companies (id, company, Country, City) values (39, 'Yacero', 'Russia', 'Sosnovo-Ozerskoye');
insert into Companies (id, company, Country, City) values (40, 'Topicshots', 'Belarus', 'Kryvichy');
insert into Companies (id, company, Country, City) values (41, 'Kare', 'Indonesia', 'Gludug');
insert into Companies (id, company, Country, City) values (42, 'Twimm', 'Russia', 'Aksha');
insert into Companies (id, company, Country, City) values (43, 'Teklist', 'Ireland', 'Monasterevin');
insert into Companies (id, company, Country, City) values (44, 'Voonix', 'Philippines', 'Manalad');
insert into Companies (id, company, Country, City) values (45, 'Eadel', 'Philippines', 'Mabalacat');
insert into Companies (id, company, Country, City) values (46, 'Tagtune', 'Indonesia', 'Sukatani');
insert into Companies (id, company, Country, City) values (47, 'Photolist', 'Brazil', 'Petrópolis');
insert into Companies (id, company, Country, City) values (48, 'Pixope', 'United States', 'Lexington');
insert into Companies (id, company, Country, City) values (49, 'Tagchat', 'Poland', 'Ciepielów');
insert into Companies (id, company, Country, City) values (50, 'Gabvine', 'Russia', 'Terney');
insert into Companies (id, company, Country, City) values (51, 'Skaboo', 'Sweden', 'Jönköping');
insert into Companies (id, company, Country, City) values (52, 'Ailane', 'Kyrgyzstan', 'Bishkek');
insert into Companies (id, company, Country, City) values (53, 'Rooxo', 'Ukraine', 'Novyy Starodub');
insert into Companies (id, company, Country, City) values (54, 'Pixonyx', 'China', 'Shihuiqiao');
insert into Companies (id, company, Country, City) values (55, 'Zoombox', 'Israel', 'Yeroẖam');
insert into Companies (id, company, Country, City) values (56, 'Agimba', 'Japan', 'Niigata-shi');
insert into Companies (id, company, Country, City) values (57, 'Wikizz', 'Indonesia', 'Balekersukamaju');
insert into Companies (id, company, Country, City) values (58, 'Avamba', 'Czech Republic', 'Skuhrov nad Bělou');
insert into Companies (id, company, Country, City) values (59, 'Photojam', 'Brazil', 'Ceará Mirim');
insert into Companies (id, company, Country, City) values (60, 'JumpXS', 'China', 'Huichang');
insert into Companies (id, company, Country, City) values (61, 'Voonte', 'Czech Republic', 'Hanušovice');
insert into Companies (id, company, Country, City) values (62, 'Oozz', 'Japan', 'Ninomiya');
insert into Companies (id, company, Country, City) values (63, 'Oyondu', 'Sweden', 'Haninge');
insert into Companies (id, company, Country, City) values (64, 'Tagfeed', 'Poland', 'Praszka');
insert into Companies (id, company, Country, City) values (65, 'Voomm', 'Portugal', 'Passos');
insert into Companies (id, company, Country, City) values (66, 'Avamm', 'China', 'Hongdu');
insert into Companies (id, company, Country, City) values (67, 'Thoughtbridge', 'Philippines', 'Anahawan');
insert into Companies (id, company, Country, City) values (68, 'Cogidoo', 'Jordan', 'As Salţ');
insert into Companies (id, company, Country, City) values (69, 'Aibox', 'Peru', 'Querocotillo');
insert into Companies (id, company, Country, City) values (70, 'Devpulse', 'China', 'Sanying');
insert into Companies (id, company, Country, City) values (71, 'Brightdog', 'Thailand', 'Kham Sakae Saeng');
insert into Companies (id, company, Country, City) values (72, 'Devpulse', 'Philippines', 'Buenlag');
insert into Companies (id, company, Country, City) values (73, 'Kazu', 'Netherlands', 'Leiden');
insert into Companies (id, company, Country, City) values (74, 'Voomm', 'Poland', 'Słubice');
insert into Companies (id, company, Country, City) values (75, 'Demimbu', 'Poland', 'Czchów');
insert into Companies (id, company, Country, City) values (76, 'Oyope', 'Egypt', 'Abū Sunbul');
insert into Companies (id, company, Country, City) values (77, 'Oba', 'Saudi Arabia', 'Al Muţayrifī');
insert into Companies (id, company, Country, City) values (78, 'Trilith', 'China', 'Chujiang');
insert into Companies (id, company, Country, City) values (79, 'Dabjam', 'Indonesia', 'Temanjang');
insert into Companies (id, company, Country, City) values (80, 'Minyx', 'China', 'Baiguo');
insert into Companies (id, company, Country, City) values (81, 'Skiba', 'Brazil', 'Capela');
insert into Companies (id, company, Country, City) values (82, 'Rhynoodle', 'Philippines', 'Bula');
insert into Companies (id, company, Country, City) values (83, 'Aimbu', 'Honduras', 'Sabanagrande');
insert into Companies (id, company, Country, City) values (84, 'Feedmix', 'Russia', 'Kamyshevatskaya');
insert into Companies (id, company, Country, City) values (85, 'Wikizz', 'Honduras', 'Valle de Ángeles');
insert into Companies (id, company, Country, City) values (86, 'Abata', 'Portugal', 'Carvalheira');
insert into Companies (id, company, Country, City) values (87, 'Quimm', 'Mexico', 'Los Mangos');
insert into Companies (id, company, Country, City) values (88, 'Thoughtstorm', 'China', 'Minle');
insert into Companies (id, company, Country, City) values (89, 'Aivee', 'Nigeria', 'Kibiya');
insert into Companies (id, company, Country, City) values (90, 'Latz', 'Portugal', 'Vagos');
insert into Companies (id, company, Country, City) values (91, 'Ailane', 'Ukraine', 'Kodra');
insert into Companies (id, company, Country, City) values (92, 'Tagfeed', 'Finland', 'Kalvola');
insert into Companies (id, company, Country, City) values (93, 'Tagfeed', 'China', 'Renhe');
insert into Companies (id, company, Country, City) values (94, 'Rhynyx', 'China', 'Huangling');
insert into Companies (id, company, Country, City) values (95, 'Eazzy', 'Spain', 'Valladolid');
insert into Companies (id, company, Country, City) values (96, 'Meeveo', 'Namibia', 'Otavi');
insert into Companies (id, company, Country, City) values (97, 'Rhybox', 'China', 'Yongdeng Chengguanzhen');
insert into Companies (id, company, Country, City) values (98, 'Skyba', 'Croatia', 'Martin');
insert into Companies (id, company, Country, City) values (99, 'Thoughtblab', 'Albania', 'Hasan');
insert into Companies (id, company, Country, City) values (100, 'Leexo', 'Armenia', 'Shahumyan');
